# -*- coding: utf-8 -*-
"""LogisticRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VsY7aqOMNHvRE_LPodtofpc28RJMDeJy
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

titanic_data=pd.read_csv('/content/titanic_train.csv')
len(titanic_data)
titanic_data.head()

titanic_data.index
titanic_data.columns

titanic_data.info()
titanic_data.describe()

sns.countplot(x='Survived',data=titanic_data)

sns.countplot(x='Survived',data=titanic_data,hue='Sex')
titanic_data.isna()

titanic_data.isna().sum()

sns.heatmap(titanic_data.isna())

(titanic_data['Age'].isna().sum()/len(titanic_data['Age']))*100
(titanic_data['Cabin'].isna().sum()/len(titanic_data['Cabin']))*100
sns.displot(x='Age',data=titanic_data)

titanic_data['Age'].fillna(titanic_data['Age'].mean(),inplace=True)
titanic_data['Age'].isna().sum()

sns.heatmap(titanic_data.isna())

titanic_data.drop('Cabin',axis=1,inplace=True)
titanic_data.head()
titanic_data.info()
titanic_data.dtypes
gender=pd.get_dummies(titanic_data['Sex'],drop_first=True)
titanic_data['Gender']=gender
titanic_data.head()

titanic_data.drop(['Name','Sex','Ticket','Embarked'],axis=1,inplace=True)
titanic_data.head()
x=titanic_data[['PassengerId','Pclass','Age','SibSp','Parch','Fare','Gender']]
y=titanic_data['Survived']
y

#import train test split method
from sklearn.model_selection import train_test_split
#train test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)
#import Logistic  Regression
from sklearn.linear_model import LogisticRegression

lr=LogisticRegression()
lr.fit(x_train,y_train)
predict=lr.predict(x_test)

#print confusion matrix
from sklearn.metrics import confusion_matrix
pd.DataFrame(confusion_matrix(y_test,predict),columns=['Predicted No','Predicted Yes'],index=['Actual No','Actual Yes'])

#import classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,predict))